<?php

########################################################################
# Extension Manager/Repository config file for ext: "tarissement"
#
# Auto generated by Extension Builder 2014-05-20
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Tarissement',
	'description' => 'Traitement sélectif au tarissement',
	'category' => 'plugin',
	'author' => 'Michel PICCIOLI',
	'author_email' => 'mpi@atolcd.fr',
	'author_company' => 'Atol Conseil & Developpement',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>